### PR TITLE
Fix flicker when entity inspector updates

### LINKED ISSUE #130: Add proper a update function to the entity inspector
It was first planed to only use the entity inspector while the simulation is paused, wich is not the way it is used right now. So a proper update mechanism should be made available and integrated in the simulation to remove the constant flicker the inspector is plagued with because it is constantly recreated.

### PR DESCRIPTION
**Pull request by buehlefs**
Refactor how the entity inspecor updates to fix ui flickering
Fixed some warnings in the UI module

Closes #130

### CODE REVIEW

File: ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java [hunk 1]
```diff
@@ -93,30 +102,130 @@ public void setName(final String name) {
...
+     */
+    public void updateEntityInspectorEntries(final EntityInspectorEntry[] entries) {
+        if (this.canUpdateValuesOnly(entries)) {
+            // only update values
+            SwingUtilities.invokeLater(() -> {
+                synchronized (this.updateLock) {
+                    // check preconditions
+                    List<Consumer<String>> valueUpdaters = this.uiValueUpdaters;
+                    if (valueUpdaters == null) return; // TODO throw exeptions here?
+                    if (valueUpdaters.size() != entries.length) return;
```
Comment (neumantm) [inline ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java:118]: I think we should throw an exception in both cases. (We should catch and log it somewhere though)

File: ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java [hunk 2]
```diff
@@ -93,30 +102,130 @@ public void setName(final String name) {
...
+     *     the name of the entry to update (additional safeguard)
      * @param value
-     *     The default/start value of the element
-     * @param callback
-     *     The callback run on value change
+     *     the new value to set for the entry
      */
-    public void addUIElement(final String name, final String type, final String value, final BiConsumer<String, String> callback) {
+    private void updateValueOnEntity(int index, String name, String value) {
+        if (this.currentEntries == null || index >= this.currentEntries.length) return;
```
Comment (neumantm) [inline ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java:196]: Maybe throw an exception? Same as above.

File: ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java [hunk 3]
```diff
@@ -93,30 +102,130 @@ public void setName(final String name) {
...
+        EntityInspectorEntry entry = this.currentEntries[index];
+        if (!entry.getName().equals(name)) return;
```
Comment (neumantm) [inline ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java:198]: Also exception?

File: ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java [hunk 4]
```diff
@@ -127,46 +236,48 @@ public void addUIElement(final String name, final String type, final String valu
...
+                updateUiValueCallback = (newValue) -> label.setText(newValue);
+                this.inspector.add(label, this.gbc);
         }
         
         this.gbc.gridx = 0;
         this.gbc.gridy += 1;
         
+        // TODO move this into outer method
         this.revalidate();
         this.repaint();
```
Comment (neumantm) [inline ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java:266]: Remove

File: ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java (hunk 1 above)
Comment (buehlefs) [reply ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java:118]: These exceptions could only happen if the update happens while the inspector is still updating. If I understand SwingUtilities.invokeLater correctly such a race condition should not happen. It is also synchronized for good measure and these checks are just to be extra sure that there will never be any exception presented to the user because the entity inspector had a bug. So throwing an exception here may not be for the best as the worst outcome is that the displayed data is from the last tick.

File: ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java (hunk 2 above)
Comment (buehlefs) [reply ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java:196]: If any of these does not match then the ui was n the middle of updating. Then it should be ok to silently dismiss the request. The user will see the ui updating and should be able to tell why the request did not work. It should also be nigh impossible to trigger this condition manually (only selecting a new entity for inspection can cause these conditions).

File: ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java (hunk 3 above)
Comment (buehlefs) [reply ICGE-Ui/src/main/java/de/unistuttgart/informatik/fius/icge/ui/internal/SwingEntityInspector.java:198]: Same as comment above.
